### ISSUE TITLE
Blender 2.72 - Cannot start plugin 

### ISSUE THREAD

**Issue by samiujan** [cedricpinson/osgexport#33]
![blendererror](https://cloud.githubusercontent.com/assets/511368/4716700/7eee79ec-590b-11e4-9375-9bac809423e8.png)

I can import the plugin but when I try to enable it, it throws an error:

from osg import data
ImportError: cannot import name 'osgdata'

I am importing the zip file from:

.\osgexport-master\blender-2.5\build\osgexport-0.14.1.zip

The zip file is attached here as well

**Comment by rugruth** [comment]
I had the same problem but managed to install and run addon in latest blender (2.76b). 

First, I changed the import lines on "\_\_init\_\_.py" to made them work in python3 import format (used in newer blender versions):

from . import bpy
from . import osg

Then I had to change line 129 as explained in another issue from this site (https://github.com/cedricpinson/osgexport/issues/25) to: 

FILE_NAME = "FILE_NAME" if bpy.app.version[0] >= 2 and bpy.app.version[1] >= 63 else "FILENAME"

That was related to changes in the blender API for writing addons. 

After that, addon worked for me without errors.

R.

**Comment by AurL** [comment]
Hi @samiujan, 

You should be able to import with version 0.14.2 (I think it is ok since it has been referenced in #34)
Let's consider it is fixed and close this issue, but don't hesitate to ping me back here if I missed something.

Thanks!
