### ISSUE TITLE
Animation: 0x250b100 RigTransformSoftware::UniqBoneSetVertexSet no bones found

### ISSUE THREAD

**Issue by maxlklaxl** [cedricpinson/osgexport#43]
I'm working on getting blender animation exported. when running from feature/blender_animation_rebuild_DEV-5604 I'm getting this msg
```
0x250b100 RigTransformSoftware::UniqBoneSetVertexSet no bones found
```
I'm running blender 2.74, osgexport-0.13.0 is working

[simple_animation.zip](https://github.com/cedricpinson/osgexport/files/61616/simple_animation.zip)

**Comment by AurL** [comment]
Hi @maxlklaxl, 

Thank you for reporting this, I am currently working on this branch and it involves a lot of changes in the way animation are exported. Your sample will be very helpful to debug, I will check that out and see what is going wrong

Thanks!

**Comment by AurL** [comment]
I couln't reproduce this error message on my side (Blender 2.76, last version of the branch). It seems that the bone is skipped by the exporter in your tries, but here the bone is still exported so RigTransforSoftware is okay. 
The branch had a few updates recently, are you up to date with it ? 
Which export options do you enable?
osgexp0142.osgt is not the export raising this warning, right ?

**Comment by maxlklaxl** [comment]
Probably I specified it not correctly. I get this msg from osganimationviewer. I checked different versions of openscenegraph, the console output of osganimationviewer changes, but the result not (animation exported with osgexporter-0.13.0 work, animations exported with osgexporter-0.14.x 'loosing' their links)

everything marked with osgexp0142 was exported with the latest version of this branch (39922985f43c9a7a456dee1fe356abe32f910c22)

1) OpenSceneGraph Library 3.0.1 (ubuntu 12.04)
a) animation exported with osgexporter 0.13.0 works
```
$ osganimationviewer osgexp0130_blender_274.osgt
LinkVisitor links 3 for "Bone"
uniq groups 1 for Cube
Play ArmatureAction
```
b) animation exported with osgexporter 0.14.2 fails to play (LinkVisitor links 0 for "Bone")
```
$ osganimationviewer osgexp0142_blender_274.osgt 
LinkVisitor links 0 for "Bone"
uniq groups 1 for Cube
RigTransformSoftware Bone "Bone" not found, skip the influence group "Bone"
0x1ecb7b0 RigTransformSoftware::UniqBoneSetVertexSet no bones found
0x1ecb7b0 RigTransformSoftware::UniqBoneSetVertexSet no bones found
.
.
.
```
2) OpenSceneGraph Library 3.2.0 (ubuntu 14.04)
a) osgexporter 0.13.0 this works fine, same as 1.a
b) osgexporter 0.14.2 this fails to play, nothing happens
```
$ osganimationviewer osgexp0142_blender_274.osgt 
LinkVisitor links 0 for "Bone"
uniq groups 1 for Cube
Play ArmatureAction
```

I did not enable or disable anything for exporting, I'm exporting from blender gui (File - Export - OSG Model)
I also checked with blender 2.74b, the result is the same
[simple_animation.zip](https://github.com/cedricpinson/osgexport/files/62410/simple_animation.zip)

**Comment by AurL** [comment]
Thanks for this detailed report!
(For info, I did my tests with OpenSceneGraph 3.3.8 on windows)

My first idea is about target names. One of the changes that is reflected when comparing `osgexp0130_blender_274.osgt` and `osgexp0142_blender_274.osgt` is that double quotes are added to target names in animation channels. I will need to do a deeper check on this but the fact that the LinkVisitors doesn't link any bones for 1.4.2 show that something goes wrong here.
You can easily test by editing the 1.4.2 osgt and remove double quotes in target names and also in "Vertex Influence" declaration. 
Could you quickly check this ? 

Thank you, and keep me in touch :)

**Comment by maxlklaxl** [comment]
thanks!

yes, removing the double quotas in TargetName and VertexInfluence fixed it

tested on ubuntu with OpenSceneGraph Library 3.0.1 and  OpenSceneGraph Library 3.2.0 

[osgexp0142_blender_274_fixed.osgt.zip](https://github.com/cedricpinson/osgexport/files/63928/osgexp0142_blender_274_fixed.osgt.zip)

**Comment by AurL** [comment]
Okay, so doing this is not safe for everyone, I 'll note it and eventually see for another solution.
You can just revert this commit to fix your issue: https://github.com/cedricpinson/osgexport/commit/4a1b61c326dbb2513d4cb4e478dfb34017bf8a16#diff-e1bf03e03e04caa0b34210cf477dec75R1300 :)
Thanks !
